site_name: HBCD Data Release

theme: 
  name: material
  features:
    - navigation.tabs
    - navigation.path
    - version

plugins:
  - search

docs_dir: docs

nav: 
  - About: index.md
  - Release Notes:
      - "Data Measures & Quality Control": measures/index.md
          - Demographics: measures/demographics.md
          - "Physical Health & Food Insecurity": measures/physhealth.md
          - Pregnancy and Exposures: measures/pregexposures.md
          - "Novel Technologies & Wearable Sensors": measures/sensors.md
          - Social and Environmental Determinants: measures/socenv_determinants.md
          - "Behavior/Caregiver Child Interaction": measures/behavior.md
          - EEG: measures/eeg.md
      - "MRI Protocols": mriprotocols/index.md
          - Siemens Protocol: mriprotocols/siemens.md
          - GE Protocol: mriprotocols/ge.md
      - "Data Curation & BIDS Data Creation": datacuration/index.md
          - Overview: datacuration/bids.md
          - Imaging Curation: datacuration/imaging.md
          - Biosensor Curation: datacuration/motion.md
          - Phenotypes Curation: datacuration/phenotypes.md
      - "Data Processing": processing/index.md
          - "Pipelines & Software Standards": processing/pipelines.md
          - External Processing Documentation: processing/processing.md
  - Change Log: changelog.md
  - FAQ: faq.md