site_name: HBCD
theme: readthedocs
plugins:
  - search
docs_dir: docs
nav:
  - Main: 
    - Release Notes: main/releasenotes.md
    - Change Log: main/changelog.md
    - FAQ: main/faq.md
  - Data Measures & Quality Control:
    - Demographics: measures/demographics.md
    - "Physical Health: Food Insecurity": measures/physhealth.md
    - Pregnancy and exposures: measures/pregexposures.md
    - Novel Technologies/Wearable Sensors: measures/sensors.md
    - Social and Environmental Determinants: measures/socenv_determinants.md
    - Behavior/Caregiver Child Interaction: measures/behavior.md
    - EEG: measures/eeg.md
  - MRI Protocols:
    - Siemens Protocol v2.2: mriprotocols/siemens.md
    - GE Protocol v2.2: mriprotocols/ge.md
  - Data Curation & BIDS Data Creation: 
    - Overview: datacuration/bids.md
    - Imaging Curation: datacuration/imaging.md
    - Biosensor Curation: motion.md
    - Phenotypes Curation: datacuration/phenotypes.md
  - Data Processing:
    - HBCD Processing: processing/processing.md
    - Pipelines: processing/pipelines.md
  
