site_name: HBCD Data Release

theme:
  name: readthedocs
  custom_dir: docs/overrides # for template overrides, used in this case for addition of "Page Last Updated: <DATE>" to pages
  features:
    - toc.integrate
    - navigation.expand
    - toc.follow
    - navigation.sections
    - header.autohide
    - content.code.annotate  

markdown_extensions:
  - toc:
      permalink: '🔗'  
  
extra_javascript:
  - js/extra.js

extra_css:
  - css/custom.css
  - css/banners.css
  - css/headers.css
  - css/tables.css
  - overrides/styles.css
  - https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css

plugins:
  - search
  - git-revision-date-localized:
      type: date

docs_dir: docs

nav: 
  - ABOUT: index.md
  - Access Data:
    - How To Access Data: data_access/index.md
    - Go To NBDC Portal: data_access/nbdcquicklink.html
    - Responsible Data Use: data_access/resp_data_use.md
    - Data Dictionary Explorer: data_access/datadictionary.md
  - Get Help:
    - FAQs: faq.md
    - Report Issues: reportissue.md
  - Release Notes:
    - "Data Measures & Quality Control":
        - Overview: measures/index.md
        - "Behavior & Caregiver-Child Interaction": measures/behCGinteraction.md   
        - Biospecimens: 
            - Overview: measures/biospecimens/index.md        
            - Blood: measures/biospecimens/blood.md
            - Nails: measures/biospecimens/nails.md 
            - Urine: measures/biospecimens/urine.md    
        - Demographics: measures/demographics.md
        - Electroencephalogram: measures/eeg/index.md
        - Magnetic Resonance Imaging:
            - Overview: measures/mri/index.md
            - Quality Control Procedures: measures/mri/qc.md
            - Structural MRI: measures/mri/smri.md
            - Functional MRI: measures/mri/fmri.md
            - Diffusion MRI: measures/mri/dmri.md
            - Quantitative MRI: measures/mri/qmri.md
            - Magnetic Resonance Spectroscopy: measures/mri/mrs.md  
        - "Neurocognition & Language": 
            - Overview: measures/neurocog/index.md    
            - MLDS: measures/neurocog/MLDS.md    
            - SPM-2: measures/neurocog/SPM2.md      
        - "Novel Technologies & Wearable Sensors": measures/sensors.md                     
        - Physical Health: measures/physicalhealth.md
        - "Pregnancy & Exposure": 
            - "Pregnancy & Infant Health": measures/pregexp/preghealth.md
            - Substance Use: measures/pregexp/substanceuse.md
            - Mental Health: measures/pregexp/mentalhealth.md
        - "Social & Environmental Determinants": measures/socenvdet.md
    - MRI Protocols: mriprotocols/mriprotocols.md
    - HBCD BIDS Data:
        - Overview: datacuration/overview.md
        - Raw Data: datacuration/rawbids.md
        - Derivatives: datacuration/derivatives.md
        - Phenotype: datacuration/phenotypes.md
        - Exclusion Criteria: datacuration/exclusions.md
    - Data Processing: 
        - Pipelines & Processing: processing/pipelines.md
        - Pipeline Software Standards: processing/standards.md
  - CHANGE LOG: 
    - Pending & Upcoming Updates: changelog/pending.md
    - Known Issues: changelog/knownissues.md
    - Version History:    
        - Beta Release 10: changelog/versions/BR10.md
        - Beta Release 9: changelog/versions/BR9.md
        - Beta Release 8: changelog/versions/BR8.md
        - Beta Release 7.5: changelog/versions/BR7.5.md
        - Beta Release 7: changelog/versions/BR7.md      
        - Beta Release 6.5: changelog/versions/BR6.5.md    
        - Beta Release 6: changelog/versions/BR6.md          
        - Beta Release 5: changelog/versions/v1.4.md
        - Beta Release 4: changelog/versions/v1.3.md
        - Beta Release 3: changelog/versions/v1.2.md
        - Beta Release 2: changelog/versions/v1.1.md
        - Beta Release 1: changelog/versions/v1.0.md
  - INTERNAL:
    - WG Report Issues: internal/reportissues.md
    - Review Beta Data Release Site: internal/beta_release_site_review.md

  

