site_name: HBCD Data Release

theme: readthedocs

extra_css:
  - css/custom.css

markdown_extensions:
  - toc:
      permalink: true

plugins:
  - search

docs_dir: docs

nav: 
  - ABOUT: index.md
  - Release Notes:
      - "Data Measures & Quality Control":
          - Overview: measures/index.md
          - Demographics: measures/demographics.md
          - "Social & Environmental Determinants":
              - Neighborhood Safety: measures/socenv_determinants/neighborhood_safety.md
              - Discrimination: measures/socenv_determinants/discrimination.md
              - PACES: measures/socenv_determinants/PACES.md
              - Perceived Stress/Social Support: measures/socenv_determinants/perceived_stress.md
              - Baby's First Year: measures/socenv_determinants/bfy.md
              - eHITS: measures/socenv_determinants/eHITS.md
          - "Neurocognition & Language": 
              - Multilingual Language Development Screener: measures/neurocog_language.md          
          - Electroencephalogram (EEG): 
              - Video Resting State: measures/eeg/video_rs.md
              - Faces Task: measures/eeg/faces_task.md
              - Auditory Mismatch Negativity Task: measures/eeg/aud_mm.md
              - Visual Evoked Potential Task: measures/eeg/vis_ep_task.md
          - Magnetic Resonance Imaging (MRI): measures/mri.md
          - "Novel Technologies & Wearable Sensors": 
              - Wearable Sensors: measures/sensors/wearable_sensors.md
              - Infant Sensor Questionnaire: measures/sensors/sensor_questionnaire.md
          - "Physical Health": measures/physhealth.md
          - "Behavior & Caregiver-Child Interaction": measures/behavior.md
          - "Pregnancy & Exposure": 
              - Pregnancy Health: measures/pregexp/preghealth.md
              - Infant Health: measures/pregexp/infant.md
              - "Psychiatric Evaluation & History": measures/pregexp/mentalhealth.md
              - Substance Use: measures/pregexp/substanceuse.md
      - "MRI Protocols": 
          - Overview: mriprotocols/overview.md
          - Siemens Protocol: mriprotocols/siemens.md
          - GE Protocol: mriprotocols/ge.md
      - HBCD BIDS Dataset:
          - Overview: datacuration/bids.md
          - Imaging: datacuration/imaging.md
          - EEG: datacuration/eeg.md
          - Motion Data: datacuration/motion.md
          - Phenotypes: datacuration/phenotypes.md
      - Data Processing: 
          - Pipelines: processing/pipelines.md
          - Pipeline Software Standards: processing/standards.md
          - External Processing Documentation: processing/processing.md
  - Change Log: 
      - Pending Updates: changelog/pending.md
      - Version History: 
          - Beta Release 5/V1.4: changelog/versions/v1.4.md
          - Beta Release 4/V1.3: changelog/versions/v1.3.md
          - Beta Release 3/V1.2: changelog/versions/v1.2.md
          - Beta Release 2/V1.1: changelog/versions/v1.1.md
          - Beta Release 1/V1.0: changelog/versions/v1.0.md

  - "FAQ & Contact": 
      - FAQ: faq.md
      - Contact: contact.md

