site_name: HBCD
theme: readthedocs
plugins:
  - search
docs_dir: docs
nav:
  - Release Notes: releasenotes.md
  - FAQ: faq.md
  - Change Log: changelog.md
  - Data Measures & Quality Control:
    - Demographics: measures/demographics.md
    - "Physical Health: Food Insecurity": measures/physhealth.md
    - Pregnancy and exposures: measures/pregexposures.md
    - Novel Technologies/Wearable Sensors: measures/sensors.md
    - Social and Environmental Determinants: measures/socenv_determinants.md
    - Behavior/Caregiver Child Interaction: measures/behavior.md
    - EEG: measures/eeg.md
  - MRI Protocols:
    - Siemens Protocol v2.2: mriprotocols/siemens.md
    - GE Protocol v2.2: mriprotocols/ge.md
  
