site_name: HBCD Data Release

theme:
  name: readthedocs
  custom_dir: docs/overrides # for template overrides
  features:
    - toc.integrate
    - navigation.expand
    - toc.follow
    - navigation.sections
    - header.autohide
    - content.code.annotate  

markdown_extensions:
  - toc:
      permalink: '🔗'  
  
extra_javascript:
  - js/extra.js

extra_css:
  - css/custom.css
  - css/banners.css
  - css/headers.css

plugins:
  - search
  - git-authors
  # - git-revision-date-localized:
  #       type: datetime
  #       locale: en
  #       fallback_to_build_date: false  # Use build date if Git history isn't available
  #       enable_creation_date: true  # Optional to display the creation date
#   - macros:
#       module_name: macros  

docs_dir: docs

nav: 
  - ABOUT: index.md
  - Access Data:
    - How To Access Data: data_access.md
    - Responsible Data Use: resp_data_use.md
    - Data Dictionary Explorer: datadictionary.md
  - Get Help:
    - FAQs: faq.md
    - Report Issues: reportissue.md
  - Release Notes:
    - "Data Measures & Quality Control":
        - Overview: measures/index.md
        - "Behavior & Caregiver-Child Interaction": 
            - Overview: measures/beh_CG_interaction/overview.md  
            - ecPROMIS: measures/beh_CG_interaction/ecPROMIS.md  
            - IBQ-R (VSF)+BI: measures/beh_CG_interaction/IBQ-R.md
            - MAPS-TL: measures/beh_CG_interaction/MAPS-TL.md    
        - Biospecimens: 
            - Blood: measures/biospecimens/blood.md
            - Nails: measures/biospecimens/nails.md 
            - Urine: measures/biospecimens/urine.md    
        - Demographics: measures/demographics.md
        - Geocoding: measures/geocoding.md
        - Electroencephalogram (EEG): 
            - Overview: measures/eeg/overview.md
            - Faces Task: measures/eeg/faces_task.md
            - Auditory Mismatch Negativity Task: measures/eeg/aud_mm.md              
            - Video Resting State: measures/eeg/video_rs.md
            - Visual Evoked Potential Task: measures/eeg/vis_ep_task.md
        - Magnetic Resonance Imaging (MRI):
            - "Overview & Raw Data QC": measures/mri/overview.md
            - Structural MRI: measures/mri/smri.md
            - Functional MRI: measures/mri/fmri.md
            - Diffusion MRI: measures/mri/dmri.md
            - Quantitative MRI: measures/mri/qmri.md
            - Magnetic Resonance Spectroscopy: measures/mri/mrs.md  
        - "Neurocognition & Language": 
            - MLDS: measures/neurocog/MLDS.md    
            - SPM-2: measures/neurocog/SPM2.md      
        - "Novel Technologies & Wearable Sensors": 
            - Wearable Sensors: measures/sensors/wearable_sensors.md
            - Infant Sensor Questionnaire: measures/sensors/sensor_questionnaire.md                          
        - Physical Health: measures/physicalhealth.md
        - "Pregnancy & Exposure": 
            - "Personal & Family Psychiatric History": measures/pregexp/psych_history.md
            - Pregnancy Health Measures: measures/pregexp/preghealth_all.md
            - Infant Health-V2: measures/pregexp/infanthealth.md
            - Substance Use Measures: measures/pregexp/substanceuse_all.md
            - Mental Health (APA 1/2): measures/pregexp/mentalhealth.md
            - DSM5 PTSD/Acute Stress: measures/pregexp/NSESSS.md
            - Postnatal Depression (EPDS): measures/pregexp/EPDS.md
        - "Social & Environmental Determinants":
            - Baby's First Years: measures/socenv_determinants/bfy.md
            - Discrimination: measures/socenv_determinants/discrimination.md 
            - Intimate Partner Violence (eHITS): measures/socenv_determinants/eHITS.md               
            - Neighborhood Safety: measures/socenv_determinants/neighborhood_safety.md  
            - PROMIS: measures/socenv_determinants/PROMIS.md
            - PACES: measures/socenv_determinants/PACES.md
    - "MRI Protocols": 
        - Overview: mriprotocols/overview.md
        - Siemens: mriprotocols/siemens.md
        - GE: mriprotocols/ge.md
        - Philips: mriprotocols/philips.md
    - HBCD BIDS Conversion:
        - Overview: datacuration/bids.md
        - Imaging: datacuration/imaging.md
        - EEG: datacuration/eeg.md
        - Motion Data: datacuration/motion.md
        - Phenotypes: datacuration/phenotypes.md
    - Data Processing: 
        - Pipelines & Processing: processing/pipelines.md
        - Pipeline Software Standards: processing/standards.md
  - CHANGE LOG: 
    - Pending & Upcoming Updates: changelog/pending.md
    - Known Issues: changelog/knownissues.md
    - Version History:    
        - Beta Release 9: changelog/versions/BR9.md
        - Beta Release 8: changelog/versions/BR8.md
        - Beta Release 7.5: changelog/versions/BR7.5.md
        - Beta Release 7: changelog/versions/BR7.md      
        - Beta Release 6.5: changelog/versions/BR6.5.md    
        - Beta Release 6: changelog/versions/BR6.md          
        - Beta Release 5: changelog/versions/v1.4.md
        - Beta Release 4: changelog/versions/v1.3.md
        - Beta Release 3: changelog/versions/v1.2.md
        - Beta Release 2: changelog/versions/v1.1.md
        - Beta Release 1: changelog/versions/v1.0.md
  - INTERNAL:
    - WG Report Issues: internal/reportissues.md
    - Review Beta Data Release Site: internal/beta_release_site_review.md
    - Information to Finalize: internal/infotofinalize.md

  

