site_name: HBCD Data Release Docs (BETA)

theme:
  name: readthedocs
  custom_dir: docs/overrides # for template overrides, used in this case for addition of "Page Last Updated: <DATE>" to pages
  features:
    - toc.integrate
    - navigation.expand
    - toc.follow
    - navigation.sections
    - header.autohide
    - content.code.annotate  

markdown_extensions:
  - toc:
      permalink: '🔗'  
  
extra_javascript:
  - js/extra.js

extra_css:
  - css/custom.css
  - css/copybox.css
  - css/banners.css
  - css/hide-sidebar.css
  - css/hoverable_elements.css
  - css/legends.css
  - css/headers.css
  - css/tables.css
  - overrides/styles.css
  - https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css
  - https://cdn.jsdelivr.net/npm/bootstrap-icons/font/bootstrap-icons.css
  - css/reduce-righthand-whitespace.css

plugins:
  - search
  - git-revision-date-localized:
      type: date

docs_dir: docs

nav: 
  - Data Usage:
    - "Access & Download Data": access/download.md
    - Responsible Data Use: access/resp_data_use.md
    - Data Use Acknowledgement: access/dua.md
  - Data Structure & File Types:
    - Structure (BIDS): datacuration/overview.md
    - Tabulated Data: datacuration/phenotypes.md
    - File-Based Data: 
        - Raw File-Based Data: datacuration/rawbids.md
        - Processed File-Based Data: datacuration/derivatives.md
        - Exclusion Criteria: datacuration/exclusions.md
    - Recommended Tools: dataformats/recprograms.md
  - Study Instruments:
    - Overview: instruments/index.md
    - Age Variables: instruments/agevariables.md
    - Behavior & Environment:
        - Behavior & Caregiver-Child Interaction: 
            - ecPROMIS: instruments/bcgi/ecpromis.md
            - IBQ-R (VSF)+BI: instruments/bcgi/ibqr.md
            - MAPS-TL: instruments/bcgi/maps-tl.md
        - Biospecimens & Omics:
            - Nails: instruments/biospec/nails.md
            - Urine: instruments/biospec/urine.md
        - Neurocognition & Language:
            - MLDS: instruments/neurocog/mlds.md
            - SPM-2: instruments/neurocog/spm2.md
        - Novel Technologies & Wearable Sensors:
            - Wearable Sensors: instruments/sensors/wearsensors.md
            - Infnat Sensor Questionnaire: instruments/sensors/questionnaire.md
        - Physical Health:
            - Breastfeeding: instruments/physhealth/bf.md
            - Food Insecurity: instruments/physhealth/foodinsecurity.md
            - Growth: instruments/physhealth/growth.md
        - Pregnancy & Exposures:
            - Pregnancy & Infant Health:
                - Pregnancy Health: instruments/pregexp/healthhx.md
                - Exposures & Vaccines: instruments/pregexp/vacc.md
                - Chronic Conditions: instruments/pregexp/chronconditions.md
                - Illness: instruments/pregexp/illness.md
                - ER/Hospitalizations: instruments/pregexp/er-hosp.md
                - Medications: instruments/pregexp/medications.md
                - End of Pregnancy: instruments/pregexp/end-preg.md
                - Infant Health: instruments/pregexp/infanthealth.md
            - Mental Health:
                - Personal & Family Psychiatric History: instruments/pregexp/fam-mh.md
                - APA 1/2: instruments/pregexp/apa12.md
                - PTSD & Acute Stress: instruments/pregexp/ptsd.md
                - Postnatal Depression: instruments/pregexp/epds.md
            - Substance Use:
                - Assist V1/2/3: instruments/pregexp/assist.md
                - TLFB: instruments/pregexp/tlfb.md
        - Social & Environmental Determinants:
            - Baby's First Years: instruments/SED/bfy.md
            - Demographics V01: instruments/SED/v01-demo.md
            - Unfair Treatment: instruments/SED/discr.md
            - Intimate Partner Violence: instruments/SED/ehits.md
            - Neighborhood Safety: instruments/SED/safety.md
            - Protective Factors: instruments/SED/paces.md
            - Perceived Stress/Social Support: instruments/SED/promis.md
    - Demographics & Visit Information:
        - Basic Demographics: instruments/demo/basicdemo.md
        - Visit Information: instruments/demo/visitinfo.md
    - Brain Activity - MRI & EEG:
        - Electroencephalography:
            - Overview & Quality Control: instruments/eeg/index.md
            - Faces Task: instruments/eeg/faces.md
            - Auditory Mismatch Negativity Task: instruments/eeg/mmn.md
            - Video Resting State Task: instruments/eeg/videors.md
            - Visual Evoked Potential Task: instruments/eeg/vep.md
        - Magnetic Resonance Imaging:
            - Overview: instruments/mri/index.md
            - MRI Protocols (Leave Site): instruments/mri/protocols.md            
            - Quality Control Procedures: instruments/mri/qc.md
            - Structural MRI: instruments/mri/smri.md
            - Functional MRI: instruments/mri/fmri.md
            - Diffusion MRI: instruments/mri/dmri.md
            - Quantitative MRI: instruments/mri/qmri.md
            - Magnetic Resonance Spectroscopy: instruments/mri/mrs.md 
  - ORGANIZE:
    - HBCD Study Design: 
        - Study Design Logic: measures/studydesign.md
        - ReproSchema: measures/reproschema.md
    - Processing & Analytic Standards: 
        - Processing Pipelines: processing/index.md
        - Pipeline Software Standards: processing/standards.md
  - Release History: 
    - Pending & Upcoming Updates: changelog/pending.md
    - Known Issues: changelog/knownissues.md
    - Version History:    
        - Release 1: changelog/versions/R1.md
  - Help & Support:
    - FAQs: help/faq.md
    - Report Issues: help/reportissue.md
    - How To Cite Release Docs: help/citation.md
 