site_name: HBCD Data Release

theme: 
  name: material
  palette:
    primary: teal
    accent: pink
  features:
    - navigation.tabs
    - navigation.path
    - version

plugins:
  - search
  - mike

docs_dir: docs

nav: 
  - About: index.md
  - Release Notes:
      - "Data Measures & Quality Control":
          - Overview: measures/index.md
          - Demographics: measures/demographics.md
          - "Physical Health: Food Insecurity": measures/physhealth.md
          - "Pregnancy & Exposures": 
              - Pregnancy Health: measures/pregexp/preghealth.md
              - Infant Health: measures/pregexp/infant.md
              - "Psychiatric Evaluation & History": measures/pregexp/mentalhealth.md
              - Substance Use: measures/pregexp/substanceuse.md
          - "Novel Technologies & Wearable Sensors": measures/sensors.md
          - "Social & Environmental Determinants": measures/socenv_determinants.md
          - "Behavior/Caregiver Child Interaction": measures/behavior.md
          - "Neurocognition & Language": measures/neurocog_language.md
          - EEG: measures/eeg.md
      - "MRI Protocols": 
          - Overview: mriprotocols/index.md
          - Siemens Protocol: mriprotocols/siemens.md
          - GE Protocol: mriprotocols/ge.md
      - "Data Curation & BIDS Data Creation":
          - Brain Imaging Data Structure: datacuration/bids.md
          - Imaging: datacuration/imaging.md
          - EEG: datacuration/eeg.md
          - Biosensor Motion Data: datacuration/motion.md
          - Phenotypes: datacuration/phenotypes.md
      - Data Processing: 
          - Pipelines: processing/pipelines.md
          - Pipeline Software Standards: processing/standards.md
          - External Processing Documentation: processing/processing.md

  - Change Log: 
      - General Settings: changelog/gensettings.md
      - Version History: 
          - V1.4: changelog/versions/v1.4.md
          - V1.3: changelog/versions/v1.3.md
          
  - FAQ: faq.md
