site_name: HBCD Data Release

theme: readthedocs
markdown_extensions:
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true

plugins:
  - search
  - mike

docs_dir: docs

nav: 
  - About: index.md
  - Release Notes:
      - "Data Measures & Quality Control":
          - Overview: measures/index.md
          - Demographics: measures/demographics.md
          - "Physical Health: Food Insecurity": measures/physhealth.md
          - "Pregnancy & Exposures": 
              - Pregnancy Health: measures/pregexp/preghealth.md
              - Infant Health: measures/pregexp/infant.md
              - "Psychiatric Evaluation & History": measures/pregexp/mentalhealth.md
              - Substance Use: measures/pregexp/substanceuse.md
          - "Novel Technologies & Wearable Sensors": measures/sensors.md
          - "Social & Environmental Determinants": measures/socenv_determinants.md
          - "Behavior/Caregiver Child Interaction": measures/behavior.md
          - "Neurocognition & Language": measures/neurocog_language.md
          - EEG: measures/eeg.md
      - "MRI Protocols": 
          - Overview: mriprotocols/index.md
          - Siemens Protocol: mriprotocols/siemens.md
          - GE Protocol: mriprotocols/ge.md
      - HBCD BIDS Dataset:
          - Brain Imaging Data Structure: datacuration/bids.md
          - Imaging: datacuration/imaging.md
          - EEG: datacuration/eeg.md
          - Motion Data: datacuration/motion.md
          - Phenotypes: datacuration/phenotypes.md
      - Data Processing: 
          - Pipelines: processing/pipelines.md
          - Pipeline Software Standards: processing/standards.md
          - External Processing Documentation: processing/processing.md
  - Change Log: 
      - General Settings: changelog/gensettings.md
      - Version History: 
          - Beta Release 5/V1.4: changelog/versions/v1.4.md
          - Beta Release 4/V1.3: changelog/versions/v1.3.md
          - Beta Release 3/V1.2: changelog/versions/v1.2.md
          - Beta Release 2/V1.1: changelog/versions/v1.1.md
          - Beta Release 1/V1.0: changelog/versions/v1.0.md
      - Phenotype Data Structure: changelog/phenotype_datastruc.md
      - Exclusion Filters: changelog/filters.md
  - FAQ: faq.md
