site_name: HBCD Data Release Docs (BETA)

theme:
  name: readthedocs
  custom_dir: docs/overrides # for template overrides, used in this case for addition of "Page Last Updated: <DATE>" to pages
  features:
    - toc.integrate
    - navigation.expand
    - toc.follow
    - navigation.sections
    - header.autohide
    - content.code.annotate  

markdown_extensions:
  - toc:
      permalink: '🔗'  
  
extra_javascript:
  - js/extra.js

extra_css:
  - css/custom.css
  - css/copybox.css
  - css/banners.css
  - css/hide-sidebar.css
  - css/hoverable_elements.css
  - css/legends.css
  - css/headers.css
  - css/tables.css
  - overrides/styles.css
  - https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css
  - https://cdn.jsdelivr.net/npm/bootstrap-icons/font/bootstrap-icons.css
  - css/reduce-righthand-whitespace.css

plugins:
  - search
  - git-revision-date-localized:
      type: date

docs_dir: docs

nav: 
  - ABOUT: index.md
  - Move to Lasso:
    - How To Access Data: lasso/duc.md
    - "Query & Download Data": lasso/download.md
  - Access Data:
    - "Access & Download Data": access/download.md
    - "Data Formats & Tools":
        - Tabulated Data: dataformats/tabulated.md
        - Recommended Programs: dataformats/recprograms.md
    - Responsible Data Use: access/resp_data_use.md
    - Data Use Acknowledgement: access/dua.md
  - Get Help:
    - FAQs: faq.md
    - Report Issues: reportissue.md
    - How To Cite Release Docs: citation.md
  - Release Notes:
    - HBCD Study Design: 
        - Study Design Logic: measures/studydesign.md
        - ReproSchema: reproschema.md
    - HBCD Data Overview:
        - BIDS Data Format: datacuration/overview.md
        - Tabulated Data: datacuration/phenotypes.md
        - Raw File-Based Data: datacuration/rawbids.md
        - Processed File-Based Data: datacuration/derivatives.md
        - Exclusion Criteria: datacuration/exclusions.md
    # - NEW HBCD Data Overview:
    #     - "Data Organization & Standards": curation/index.md
    - "Data Measures & Quality Control":
        - Overview: measures/index.md
        - Age Variables: measures/agevariables.md
        - "Demographics": measures/demographics.md
        - "Behavior & Caregiver-Child Interaction": measures/behCGinteraction.md   
        - Biospecimens: measures/biospec.md   
        - "Neurocognition & Language": measures/neurocog.md    
        - "Novel Technologies & Wearable Sensors": measures/sensors.md                     
        - Physical Health: measures/physicalhealth.md
        - "Pregnancy & Exposure": 
            - "Pregnancy & Infant Health": measures/pregexp/preghealth.md
            - Substance Use: measures/pregexp/substanceuse.md
            - Mental Health: measures/pregexp/mentalhealth.md
        - "Social & Environmental Determinants": measures/socenvdet.md
        - Electroencephalography: measures/eeg/index.md
        - Magnetic Resonance Imaging:
            - Overview: measures/mri/index.md
            - MRI Protocols (Leave Site): measures/mri/protocols.md            
            - Quality Control Procedures: measures/mri/qc.md
            - Structural MRI: measures/mri/smri.md
            - Functional MRI: measures/mri/fmri.md
            - Diffusion MRI: measures/mri/dmri.md
            - Quantitative MRI: measures/mri/qmri.md
            - Magnetic Resonance Spectroscopy: measures/mri/mrs.md 
    - Data Processing: 
        - Processing Pipelines: processing/index.md
        - Pipeline Software Standards: processing/standards.md
  - CHANGE LOG: 
    - Pending & Upcoming Updates: changelog/pending.md
    - Known Issues: changelog/knownissues.md
    - Version History:    
        - Release 1: changelog/versions/R1.md

  

