name: Release a repo with tag

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      title:
        description: 'Release title: some special text for the release, version number used if not provided'
        required: false
        default: ''

jobs:
  release_pkg:
    uses: DCAN-Labs/dsm-gha-release_repo/.github/workflows/workflow.yml@main
    secrets: inherit
    with:
      remote_owner: 'DCAN-Labs'
      remote_repo: 'hbcd-docs'
      release_title: ${{ inputs.title }}
      version_major: ${{ vars.VAR_RELEASE_VERSION_MAJOR }}
      is_pkg: false
      exclude: '.github/*'
